[CI] Run debugger with backtrace in case of C++ tests failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -276,7 +276,7 @@ jobs:
       - name: Prepare env
         run: >
           apt-get update && apt-get install -y python3-dev python3-pip python3-setuptools python3-wheel python3-venv
-          libboost-filesystem-dev --no-install-recommends
+          libboost-filesystem-dev gdb --no-install-recommends
 
       - name: Setup CCache
         uses: hendrikmuhs/ccache-action@v1.2.2
@@ -332,6 +332,46 @@ jobs:
           cd build
           catchsegv ctest --output-on-failure
 
+      - name: Run debugger in case of failure
+        if: ${{ failure() }}
+        run: |
+          cd build
+          ctest --output-on-failure > ctest_output.txt || true
+
+          sed -e '1,/The following tests FAILED:/ d' ctest_output.txt \
+              | cut -d '-' -f2 \
+              | sed -e 's/ (SEGFAULT)//' -e 's/ *$//g' -e 's/^ *//g' > failed_tests.txt
+
+          ctest -V -N \
+              | grep 'Test command' \
+              | cut -d ':' -f3 \
+              | sed -e 's/ *$//g' -e 's/^ *//g' > test_commands.txt
+
+          while read name; do
+              echo "Processing $name"
+              cmd=$(grep "$name" test_commands.txt)
+
+              if [ -z "$cmd" ]; then
+                  echo "  -> skipping because cannot find command in command list!"
+                  continue
+              fi
+
+              # lines are of the form /path/to/test/executable "Some Filter"
+              program=$(echo "$cmd" \
+                            | cut -d'"' -f1\
+                            | sed -e 's/ *$//g' -e 's/^ *//g')
+              args=$(echo "$cmd" \
+                         | sed -e "s|$program||" -e 's/ *$//g' -e 's/^ *//g')
+
+              if [ -z "$program" ]; then
+                  echo "  -> skipping because cannot extract program from command line!"
+                  continue
+              fi
+
+              gdb --batch -ex 'run' -ex 'thread apply all bt' -ex 'quit' --args "$program" "$args"
+              # lldb --batch -o "file $program" -o "run $args" -k 'bt all' -o 'quit'
+          done < failed_tests.txt
+
       - name: Save tests executable in case of failure
         if: ${{ failure() }}
         uses: actions/upload-artifact@v3
@@ -376,7 +416,7 @@ jobs:
       - name: Prepare env
         run: >
           apt-get update && apt-get install -y python3-dev python3-pip python3-setuptools python3-wheel python3-venv
-          --no-install-recommends
+          gdb --no-install-recommends
 
       - name: Setup CCache
         uses: hendrikmuhs/ccache-action@v1.2.2
@@ -440,6 +480,46 @@ jobs:
         run: |
           cd build
           catchsegv ctest --output-on-failure
+
+      - name: Run debugger in case of failure
+        if: ${{ failure() }}
+        run: |
+          cd build
+          ctest --output-on-failure > ctest_output.txt || true
+
+          sed -e '1,/The following tests FAILED:/ d' ctest_output.txt \
+              | cut -d '-' -f2 \
+              | sed -e 's/ (SEGFAULT)//' -e 's/ *$//g' -e 's/^ *//g' > failed_tests.txt
+
+          ctest -V -N \
+              | grep 'Test command' \
+              | cut -d ':' -f3 \
+              | sed -e 's/ *$//g' -e 's/^ *//g' > test_commands.txt
+
+          while read name; do
+              echo "Processing $name"
+              cmd=$(grep "$name" test_commands.txt)
+
+              if [ -z "$cmd" ]; then
+                  echo "  -> skipping because cannot find command in command list!"
+                  continue
+              fi
+
+              # lines are of the form /path/to/test/executable "Some Filter"
+              program=$(echo "$cmd" \
+                            | cut -d'"' -f1\
+                            | sed -e 's/ *$//g' -e 's/^ *//g')
+              args=$(echo "$cmd" \
+                         | sed -e "s|$program||" -e 's/ *$//g' -e 's/^ *//g')
+
+              if [ -z "$program" ]; then
+                  echo "  -> skipping because cannot extract program from command line!"
+                  continue
+              fi
+
+              gdb --batch -ex 'run' -ex 'thread apply all bt' -ex 'quit' --args "$program" "$args"
+              # lldb --batch -o "file $program" -o "run $args" -k 'bt all' -o 'quit'
+          done < failed_tests.txt
 
       - name: Save tests executable in case of failure
         if: ${{ failure() }}
